import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'react-toastify/dist/ReactToastify.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import '@fortawesome/fontawesome-free/css/all.min.css'
import { ToastContainer } from "react-toastify";
import { Container } from "react-bootstrap";
import Sidebar from "@/components/sidebar";
import "@/styles/layout.css"
import Search from "@/components/search";
import Image from 'next/image'
import { HandleDayTime } from "@/utils/handle-day-time";
const inter = Inter({ subsets: ["latin"] });

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let  isDay:boolean = HandleDayTime();
  const backgroundStyle = {
    backgroundImage: isDay 
      ? 'url("/images/background-day.jpg")' 
      : 'url("/images/background-night.jpg")',
    margin:'0',
    padding: '0'
  };

  return (
    <html lang="en"   suppressHydrationWarning>
      <body className={`${inter.className}`} style={backgroundStyle}>
        <Container fluid className="container-fluid__Container" >
      
          <div className="row container-row__div" >
            <div className="col-1 col-sidebar__div" >
              <Sidebar />
            </div>
            <div className="col-11 col-children__div" >

              {children}
              <ToastContainer
                position="top-right"
                autoClose={5000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="light" />
              {/* Same as */}
              <ToastContainer />
            </div>
          </div>
        </Container>

      </body>
    </html>
  );
}
